language: python

env:
  - TF_INPUT=false

matrix:
  include:
  - name: "Ansible Tests"
    python: "2.7"
    env: TEST_TYPE="ansible"
  - name: "Terraform Tests"
    python: "2.7"
    env: TEST_TYPE="terraform"

install:
  - if [ "${TEST_TYPE}" == "ansible" ]; then
      echo "Install Ansible requirements";
      pip install -r requirements.txt;
    elif [ "${TEST_TYPE}" == "terraform" ]; then
      echo "Setting up Terraform and IBM provider";
      ./setup_terraform.sh ci;
    else
      echo "TEST_TYPE is not set. Please check your matrix settings in .travis.yml";
    fi

script:
  - if [ "${TEST_TYPE}" == "ansible" ]; then
      echo "Running Ansible linting";
      ansible-lint reference_cluster/ansible/playbook.yml;
    elif [ "${TEST_TYPE}" == "terraform" ]; then
      export PATH="${PATH}:$(pwd)/bin";
      echo "Running Terraform validation";
      cd reference_cluster;
      terraform init;
      terraform validate -check-variables=true;
    else
      echo "TEST_TYPE is not set. Please check your matrix settings in .travis.yml";
    fi